
{{< pagebreak >}}

# Appendices {.appendix}

## Appendix A: Standard Errors$\textemdash$Statistical Inference in a Nutshell

Say I wish to find the mean weight $\mu$ of all students at the University of
California, Davis.  It would be infeasible to measure them all, so I
take a random sample of 100 students.  The mean weight of those 100
students, denoted $\bar{X}$, is an estimate of $\mu$.

I know that $\bar{X}$ will have some unknowm amount of error as an estimate of
$\mu$.  One measure of this is its *standard error* (SE).  What is this?

Remember, we took a random sample of students.  Different samples will
have different values of $\bar{X}$, i.e. $\bar{X}$ will have *sampling
variation*.  Then the SE of $\bar{X}$ is defined to be the standard
deviation of all possible $\bar{X}$ values, from all possible samples.

The smaller the SE is, the more confident we are that the $\bar{X}$ from
[Meaning of that 95% probability figure: Think of all possible 
samples. Each one has an $\bar{X}$ value, and an SE value. So, each
possible sample, there is a different confidence interval (CI). 
95% of those CIs will contain the true $\mu$.]{.column-margin}
our particular sample is pretty accurate.  Of course, we can't be
completely sure, but we can quantify it probabilistically:

> An approximate 95% *confidence interval* for $\mu$, based on
> $\bar{X}$, is $\bar{X} \pm 1.96 \times SE$.

The reader may have heard of the Central Limit Theorem, which says that
the sum of many random variables, itself a random variable, has an
approximately normal distribution.  This is the case for most classical
statistical estimators, such as estimated coefficients in linear and
generalized linear models.  Hence we can find confidence intervals as
above, taking the estimator plus and minus 1.96 times the SE of the
estimator.

CIs are generally taught together with *hypothesis testing* or
*significance testing*, which in many cases uses standard errors.  
@sec-sig reviews the notion, and discusses problems with this kind of
analysis.

## Appendix B: Standard Errors via the Bootstrap {#sec-boot}

(to be added)

## Appendix C: Python Interface 

As previously mentioned, Python wrappers are included for most functions. 

### Requirements For All Python Functions

To use these Python functions, users need to have Python version **3.10** 
installed on their system. 

If the user has a later version of Python 
installed (such as 3.11), and wants to keep that version of Python in 
their system, they will have to manage multiple Python versions on their 
system. One easy way to manage multiple environments 
(in our case, multiple versions of Python for users who need it) is to 
use [Conda](https://docs.conda.io/projects/conda/en/stable/), which is 
a package and environment manager included in both 
[Anaconda](https://docs.conda.io/projects/conda/en/stable/glossary.html#anaconda-glossary) 
and [Miniconda](https://docs.conda.io/projects/conda/en/stable/glossary.html#miniconda-glossary).
For our purposes, Miniconda is more useful as a minimalistic way to install 
and use Conda. See [this guide](https://docs.conda.io/projects/miniconda/en/latest/) 
for information on how to install Miniconda -- keep in mind that, at 
this time, this package requires Python 3.10 (NOT the latest version of 
Python), so when the guide prompts you to choose a Miniconda installer, 
you can choose a link for Python 3.10 from this 
[list](https://docs.conda.io/projects/miniconda/en/latest/miniconda-other-installer-links.html)
which is also linked in the aforementioned guide.

After installing miniconda, refer to [this section](https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-environments.html) 
and later sections of the Conda user guide to set up an environment with 
Python 3.10.

Python 3.10 conveniently comes with **pip**, the Python package installer. 
It can be used to install various Python packages/modules that will be 
required to run the dsld Python functions. **All** of our Python functions
[To install rpy2, run **pip install rpy2** within the Python 3.10 environment, 
or see [this link](https://rpy2.github.io/doc/latest/html/overview.html#install-from-source)]{.column-margin} 
require **rpy2**, which allows for Python/R environment interaction.

### Running dsld Python Functions

As an example, let's use the Python interface for ##dsldTakeALookAround## 
(the Python-equivalent function is called **dsldPyTakeALookAround**)  
to view tabular information on how data features relate to Y and S. The 
Python function allows users to enter arguments using Python data types 
and converts the resultant R dataframe into a Pandas dataframe.

Different Python functions will require different libraries 
depending on what the function does -- **Pandas**
[These libraries can also (usually) be installed with **pip**]{.column-margin} 
is required for dsldPyTakeALookAround.

<!-- This part may change if installation method changes -- assuming that we 
are using devtools::install_github and have access to /dsld folder -->
The user should open the Python Shell Prompt by typing **python** from the 
package Python directory (/dsld/inst/Python) in the terminal/cmd prompt.
Then, to run the Python function, we can run the following commands in the 
Python shell:

```python}
from dsldTakeALook_Py_R import dsldPyTakeALookAround    
import rpy2.robjects as robjects   
robjects.r['data']('svcensus')    
data = robjects.r('svcensus')    
result = dsldPyTakeALookAround(data, 'wageinc', 'gender')   
print(result)
```

The result should be the same information from the R dataframe, but 
converted to a Pandas dataframe.
